In [2]:
#Import modul
from pandas.core.frame import DataFrame
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import scipy.stats as stats
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

#Membaca data
data = pd.read_csv("Qris.csv")
df = pd.DataFrame(data)
print(df)

#Pengecekkan missing value -- tidak ada missing value setelah code dijalankan
print("===================================================================================================")
print("Pengecekkan missing value")
dataMiss = df.isna().sum()
print(dataMiss)

df = pd.DataFrame(data)

               Timestamp                        Nama  Umur Jenis Kelamin  \
0    02/10/2023 15:16:19                       Abram    20     Laki-laki
1    02/10/2023 15:39:19                   Airlangga    20     Laki-laki
2    02/10/2023 15:45:11                       Wangi    20     Perempuan
3    02/10/2023 15:51:21   Muhammad Rifki Ubaedillah    24     Laki-laki
4    02/10/2023 16:01:56  Ni Kadek Rosa Amalia Putri    21     Perempuan
..                   ...                         ...   ...           ...
110  11/10/2023 18:07:55                 Dwi Sucipto    22     Laki-laki
111  12/10/2023 21:37:13                        Lina    26     Perempuan
112   13/10/2023 9:30:12                        aufa    21     Perempuan
113  13/10/2023 14:05:16                        Fika    21     Perempuan
114  13/10/2023 17:02:33                        Tyas    22     Perempuan

    Status pekerjaan Pendapatan per bulan  \
0       Sedang studi   Kurang dari 2 juta
1       Sedang studi   Kurang dari 2 juta
2       Sedang studi   Kurang dari 2 juta
3            Lainnya   Kurang dari 2 juta
4       Sedang studi   Kurang dari 2 juta
..               ...                  ...
110          Bekerja            5-10 juta
111          Lainnya   Kurang dari 2 juta
112     Sedang studi   Kurang dari 2 juta
113     Sedang studi   Kurang dari 2 juta
114     Sedang studi             2-5 juta

    Apakah Anda mengetahui apa itu QRIS? Sejak kapan Anda mengetahui QRIS?  \
0                                     Ya                     Baru-baru ini
1                                     Ya                     Baru-baru ini
2                                     Ya                        Sejak 2019
3                                     Ya                        Sejak 2019
4                                     Ya                     Baru-baru ini
..                                   ...                               ...
110                                   Ya                        Sejak 2019
111                                   Ya                     Baru-baru ini
112                                   Ya                        Sejak 2019
113                                   Ya                        Sejak 2019
114                                   Ya                     Baru-baru ini

     Seberapa sering Anda menggunakan QRIS dalam transaksi sehari-hari?  \
0                                                    5
1                                                    5
2                                                    4
3                                                    5
4                                                    5
..                                                 ...
110                                                  5
111                                                  5
112                                                  2
113                                                  2
114                                                  5

     Bagaimana pengalaman Anda menggunakan QRIS dalam bertransaksi?  \
0                                                    4
1                                                    5
2                                                    4
3                                                    4
4                                                    5
..                                                 ...
110                                                  4
111                                                  5
112                                                  5
113                                                  5
114                                                  5

    Apakah Anda merasa lebih efisien menggunakan QRIS dibandingkan dengan metode pembayaran lain?  \
0                                          Tidak yakin
1                                                   Ya
2                                                   Ya
3                                          Tidak yakin
4                                                   Ya
..                                                 ...
110                                                 Ya
111                                                 Ya
112                                        Tidak yakin
113                                        Tidak yakin
114                                                 Ya

     Seberapa percaya Anda terhadap keamanan QRIS dalam melakukan transaksi?  \
0                                                    3
1                                                    5
2                                                    3
3                                                    2
4                                                    5
..                                                 ...
110                                                  4
111                                                  5
112                                                  3
113                                                  5
114                                                  5

    Apakah Anda pernah mengalami masalah keamanan (seperti kebocoran pin) saat menggunakan QRIS?  \
0                                                Tidak
1                                                Tidak
2                                                Tidak
3                                                Tidak
4                                          Tidak yakin
..                                                 ...
110                                              Tidak
111                                              Tidak
112                                              Tidak
113                                              Tidak
114                                        Tidak yakin

    Apakah penggunaan QRIS meningkatkan kecenderungan Anda untuk berbelanja secara impulsif?  \
0                                                Tidak
1                                                   Ya
2                                                   Ya
3                                                   Ya
4                                          Tidak yakin
..                                                 ...
110                                              Tidak
111                                        Tidak yakin
112                                        Tidak yakin
113                                              Tidak
114                                              Tidak

    Apakah Anda cenderung menghabiskan lebih banyak uang setelah menggunakan QRIS?  \
0                                                Tidak
1                                                   Ya
2                                                   Ya
3                                                   Ya
4                                                   Ya
..                                                 ...
110                                              Tidak
111                                                 Ya
112                                        Tidak yakin
113                                              Tidak
114                                              Tidak

     Bagaimana menurut Anda pengaruh QRIS terhadap pola pengeluaran bulanan Anda?
0                                                    2
1                                                    2
2                                                    3
3                                                    3
4                                                    3
..                                                 ...
110                                                  2
111                                                  2
112                                                  2
113                                                  2
114                                                  2

[115 rows x 16 columns]
===================================================================================================
Pengecekkan missing value
Timestamp                                                                                        0
Nama                                                                                             0
Umur                                                                                             0
Jenis Kelamin                                                                                    0
Status pekerjaan                                                                                 0
Pendapatan per bulan                                                                             0
Apakah Anda mengetahui apa itu QRIS?                                                             0
Sejak kapan Anda mengetahui QRIS?                                                                0
Seberapa sering Anda menggunakan QRIS dalam transaksi sehari-hari?                               0
Bagaimana pengalaman Anda menggunakan QRIS dalam bertransaksi?                                   0
Apakah Anda merasa lebih efisien menggunakan QRIS dibandingkan dengan metode pembayaran lain?    0
Seberapa percaya Anda terhadap keamanan QRIS dalam melakukan transaksi?                          0
Apakah Anda pernah mengalami masalah keamanan (seperti kebocoran pin) saat menggunakan QRIS?     0
Apakah penggunaan QRIS meningkatkan kecenderungan Anda untuk berbelanja secara impulsif?         0
Apakah Anda cenderung menghabiskan lebih banyak uang setelah menggunakan QRIS?                   0
Bagaimana menurut Anda pengaruh QRIS terhadap pola pengeluaran bulanan Anda?                     0
dtype: int64

In [3]:
df.rename(columns={'Apakah Anda mengetahui apa itu QRIS?':'Atensi_qris',
                   'Sejak kapan Anda mengetahui QRIS?': 'Atensi_pertama_QRIS',
                   'Seberapa sering Anda menggunakan QRIS dalam transaksi sehari-hari?': 'Frekuensi',
                   'Bagaimana pengalaman Anda menggunakan QRIS dalam bertransaksi?':'Pengalaman_pengguna' ,
                   'Apakah Anda merasa lebih efisien menggunakan QRIS dibandingkan dengan metode pembayaran lain?':'Efisiensi',
                   'Seberapa percaya Anda terhadap keamanan QRIS dalam melakukan transaksi?': 'Kepercayaan_pengguna',
                   'Apakah Anda pernah mengalami masalah keamanan (seperti kebocoran pin) saat menggunakan QRIS?':'keamanan',
                   'Apakah penggunaan QRIS meningkatkan kecenderungan Anda untuk berbelanja secara impulsif?':'Impulsif',
                   'Apakah Anda cenderung menghabiskan lebih banyak uang setelah menggunakan QRIS?':'Kencenderungan_menghabiskan_uang',
                   'Bagaimana menurut Anda pengaruh QRIS terhadap pola pengeluaran bulanan Anda?':'Pengaruh_QRIS_thd_Pengeluaran'}, inplace=True)
df.head()

,Timestamp,Nama,Umur,Jenis Kelamin,Status pekerjaan,Pendapatan per bulan,Atensi_qris,Atensi_pertama_QRIS,Frekuensi,Pengalaman_pengguna,Efisiensi,Kepercayaan_pengguna,keamanan,Impulsif,Kencenderungan_menghabiskan_uang,Pengaruh_QRIS_thd_Pengeluaran
0,02/10/2023 15:16:19,Abram,20,Laki-laki,Sedang studi,Kurang dari 2 juta,Ya,Baru-baru ini,5,4,Tidak yakin,3,Tidak,Tidak,Tidak,2
1,02/10/2023 15:39:19,Airlangga,20,Laki-laki,Sedang studi,Kurang dari 2 juta,Ya,Baru-baru ini,5,5,Ya,5,Tidak,Ya,Ya,2
2,02/10/2023 15:45:11,Wangi,20,Perempuan,Sedang studi,Kurang dari 2 juta,Ya,Sejak 2019,4,4,Ya,3,Tidak,Ya,Ya,3
3,02/10/2023 15:51:21,Muhammad Rifki Ubaedillah,24,Laki-laki,Lainnya,Kurang dari 2 juta,Ya,Sejak 2019,5,4,Tidak yakin,2,Tidak,Ya,Ya,3
4,02/10/2023 16:01:56,Ni Kadek Rosa Amalia Putri,21,Perempuan,Sedang studi,Kurang dari 2 juta,Ya,Baru-baru ini,5,5,Ya,5,Tidak yakin,Tidak yakin,Ya,3

In [4]:
df['Jenis Kelamin'] = df['Jenis Kelamin'].replace({'Laki-laki' : 0, "Perempuan" : 1})
df['Status pekerjaan'] = df['Status pekerjaan'].replace({'Sedang studi' : 0, "Bekerja" : 1, "Lainnya" : 2})
df['Pendapatan per bulan'] = df['Pendapatan per bulan'].replace({'Kurang dari 2 juta' : 0, "2-5 juta" : 1, "5-10 juta" :2, "Lebih dari 10 juta" :3})
df['Atensi_qris'] = df['Atensi_qris'].replace({'Tidak' : 0, "Ya" : 1})
df['Atensi_pertama_QRIS'] = df['Atensi_pertama_QRIS'].replace({'Baru-baru ini' : 0, "Sejak 2019" : 1})
df['Efisiensi'] = df['Efisiensi'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['keamanan'] = df['keamanan'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['Impulsif'] = df['Impulsif'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['Kencenderungan_menghabiskan_uang'] = df['Kencenderungan_menghabiskan_uang'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})

df.head()

,Timestamp,Nama,Umur,Jenis Kelamin,Status pekerjaan,Pendapatan per bulan,Atensi_qris,Atensi_pertama_QRIS,Frekuensi,Pengalaman_pengguna,Efisiensi,Kepercayaan_pengguna,keamanan,Impulsif,Kencenderungan_menghabiskan_uang,Pengaruh_QRIS_thd_Pengeluaran
0,02/10/2023 15:16:19,Abram,20,0,0,0,1,0,5,4,1,3,0,0,0,2
1,02/10/2023 15:39:19,Airlangga,20,0,0,0,1,0,5,5,2,5,0,2,2,2
2,02/10/2023 15:45:11,Wangi,20,1,0,0,1,1,4,4,2,3,0,2,2,3
3,02/10/2023 15:51:21,Muhammad Rifki Ubaedillah,24,0,2,0,1,1,5,4,1,2,0,2,2,3
4,02/10/2023 16:01:56,Ni Kadek Rosa Amalia Putri,21,1,0,0,1,0,5,5,2,5,1,1,2,3

In [5]:
# Menggunakan OrdinalEncoder untuk mengubah data ordinal menjadi angka
ordinal_encoder = OrdinalEncoder()
df['Jenis Kelamin_encoded'] = ordinal_encoder.fit_transform(df[['Jenis Kelamin']])
df['Status pekerjaan_encoded'] = ordinal_encoder.fit_transform(df[['Status pekerjaan']])
df['Pendapatan per bulan_encoded'] = ordinal_encoder.fit_transform(df[['Pendapatan per bulan']])
df['Atensi_qris_encoded'] = ordinal_encoder.fit_transform(df[['Atensi_qris']])
df['Atensi_pertama_QRIS_encoded'] = ordinal_encoder.fit_transform(df[['Atensi_pertama_QRIS']])
df['Frekuensi_encoded'] = ordinal_encoder.fit_transform(df[['Frekuensi']])
df['Pengalaman_pengguna_encoded'] = ordinal_encoder.fit_transform(df[['Pengalaman_pengguna']])
df['Efisiensi_encoded'] = ordinal_encoder.fit_transform(df[['Efisiensi']])
df['Kepercayaan_pengguna_encoded'] = ordinal_encoder.fit_transform(df[['Kepercayaan_pengguna']])
df['keamanan_encoded'] = ordinal_encoder.fit_transform(df[['keamanan']])
df['Impulsif_encoded'] = ordinal_encoder.fit_transform(df[['Impulsif']])
df['Kencenderungan_menghabiskan_uang_encoded'] = ordinal_encoder.fit_transform(df[['Kencenderungan_menghabiskan_uang']])
df['Pengaruh_QRIS_thd_Pengeluaran_encoded'] = ordinal_encoder.fit_transform(df[['Pengaruh_QRIS_thd_Pengeluaran']])

In [6]:
# Pemilihan fitur dengan SelectKBest dan chi-squared sebagai skor
X = df[['Umur','Jenis Kelamin','Status pekerjaan_encoded','Pendapatan per bulan_encoded','Atensi_qris_encoded',
        'Atensi_pertama_QRIS_encoded','Frekuensi_encoded','Pengalaman_pengguna_encoded','Efisiensi_encoded','Kepercayaan_pengguna_encoded',
        'keamanan_encoded','Impulsif_encoded','Kencenderungan_menghabiskan_uang_encoded','Pengaruh_QRIS_thd_Pengeluaran_encoded']]
y = df['Impulsif_encoded']
# Pilih 7 fitur terbaik
k_best = SelectKBest(score_func=chi2, k=7)
X_new = k_best.fit_transform(X, y)

# Tampilkan fitur terpilih
selected_features = X.columns[k_best.get_support()]
print("Fitur terpilih:", selected_features)

Fitur terpilih: Index(['Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded', 'Impulsif_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded'],
      dtype='object')

In [7]:
#Mendefinisikan ulang data dengan fitur hasil seleksi
data = df[['Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded', 'Impulsif_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded']]
df = pd.DataFrame(data)
df.head()

,Status pekerjaan_encoded,Pendapatan per bulan_encoded,Frekuensi_encoded,keamanan_encoded,Impulsif_encoded,Kencenderungan_menghabiskan_uang_encoded,Pengaruh_QRIS_thd_Pengeluaran_encoded
0,0.0,0.0,4.0,0.0,0.0,0.0,1.0
1,0.0,0.0,4.0,0.0,2.0,2.0,1.0
2,0.0,0.0,3.0,0.0,2.0,2.0,2.0
3,2.0,0.0,4.0,0.0,2.0,2.0,2.0
4,0.0,0.0,4.0,1.0,1.0,2.0,2.0

In [8]:
#Deteksi outlier-- tidak ada outlier setelah code dijalankan
df = df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]
variabel = ('Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded', 'Impulsif_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded')
outliers = []
def detect_outlier(df):

    threshold = 3
    mean_1 = np.mean(df)
    std_1 = np.std(df)

    for y in df:
        z_score= (y - mean_1)/std_1
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers

for var in variabel:
    outlier_datapoints = detect_outlier(df[var])
    print("Outlier ", var, " = ", outlier_datapoints)

print()

Outlier  Status pekerjaan_encoded  =  []
Outlier  Pendapatan per bulan_encoded  =  []
Outlier  Frekuensi_encoded  =  []
Outlier  keamanan_encoded  =  []
Outlier  Impulsif_encoded  =  []
Outlier  Kencenderungan_menghabiskan_uang_encoded  =  []
Outlier  Pengaruh_QRIS_thd_Pengeluaran_encoded  =  []

In [9]:
# Split data menjadi fitur (X) dan target (y)
X = df.drop(columns=['Impulsif_encoded'])
y = df['Impulsif_encoded']

# Manually split the data into training and testing sets
X_train = np.concatenate((X.iloc[1:38, :], X.iloc[55:88, :], X.iloc[95:115, :]), axis=0)
X_test = np.concatenate((X.iloc[38:55, :], X.iloc[88:95, :]), axis=0)
y_train = np.concatenate((y.iloc[1:38], y.iloc[55:88], y.iloc[95:115]), axis=0)
y_test = np.concatenate((y.iloc[38:55], y.iloc[88:95]), axis=0)


# Standardize the data
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# Create and train the classifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

# Make predictions
y_pred = classifier.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Classification report
print(classification_report(y_test, y_pred))

Accuracy: 0.7916666666666666
              precision    recall  f1-score   support

         0.0       0.78      0.78      0.78         9
         1.0       0.75      0.50      0.60         6
         2.0       0.82      1.00      0.90         9

    accuracy                           0.79        24
   macro avg       0.78      0.76      0.76        24
weighted avg       0.79      0.79      0.78        24

In [10]:
# ######################## klasifikasi ##########################################
# # Split data menjadi fitur (X) dan target (y)
# X = df.drop(columns=['Impulsif_encoded'])
# y = df['Impulsif_encoded']

# # Split data menjadi data latih dan data uji
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=35)

# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# classifier = RandomForestClassifier()
# classifier.fit(X_train, y_train)


# # Membuat prediksi
# y_pred = classifier.predict(X_test)

# # Evaluasi model
# from sklearn.metrics import accuracy_score, classification_report
# accuracy = accuracy_score(y_test, y_pred)
# print(f'Accuracy: {accuracy}')

# # Laporan klasifikasi
# print(classification_report(y_test, y_pred))

In [11]:
pickle.dump(classifier, open("model.pkl", "wb"))